* zeromq介绍
** what, why, how
*** what
    zeromq是一个队列通讯库(library), 用来解决进程/线程之间消息通讯的问题.
*** why
    socket/select/poll/ hard/complex/diffcult
    rebbitmq? 跑服务, 不爽直, 还是有点复杂
*** how
    only sockets! create, bind/connect, send/recv
    send messages!
*** lots of examples
**** caculate server
     简单的一个流程
     client - caculator
**** dync timer server
     pub/sub, pull/push
     client - time server - caculator
**** snake-challenge
     server:
     send/recv - 请求
     puber - 地图更新
**** async server: ballencer
     async
     recv到的是: [id, '', msg]
     发送也是: [id, '', msg]
     client - time server - ballencer - caculator
**** map/reduce
     client - mapper - work_dister - wd... - worker
**** 负载均衡集群!
     图片
** 遇到的问题
   一个例子.. socket通讯
   教科书create socket, listen, fork/process.., 处理多个请求, 什么, 后台还要跑东西.. 换平台?
   难用, 容易出错, 性能不好, 有什么好用的解决方案没有?
** zeromq
   定义socket, connect/bind接口, send/recv, 轻松解决! douban/4chan
** zeromq性能
   比xxx好5倍!
** 一些经典模式
   req/rep, pub/sub, xreq/xrev
** 好用的例子
   官方提示
*** 任务发布(map/reduce?)
*** 广播监控
    server: pub, pull
    client: sub, push
*** 分布式负载均衡
    看官方教程! 上图片! 普通程序员也能搭建集群!
** thanks!
   人生苦短, 我用zeromq.
   有问题找党员 -> zeromq doc/maillist
* 补充
** socket错误处理, 包检测, 重发..
** zeromq神奇之处: 
   server/client不互相依赖  
   c/c++/ruby/python...
   snake-challenge
