apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  labels:
    app: node-web-app
spec:
  replicas: 1
  selector:
    matchLabels:
      service: webapp
  template:
    metadata:
      labels:
        app: node-web-app
        service: webapp
    spec:
      containers:
        - name: webapp
          image: halida/node-web-app
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: webapp
  labels:
    app: node-web-app
    service: webapp
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    service: webapp
